---
# tasks to configure the slave nodes

# copyting the sysctl file
- name: "Copying files for sysctl"
  copy:
    dest: "/etc/sysctl.d/k8s.conf"
    src: "k8s.conf"
# restarting the sysctl
- name: "Restarting the sysctl"
  shell: "sysctl --system"
# joining the slave to the master using the join command
- name: "Joining the slave nodes to the master node"
  shell: "{{ joinCommand }}"